# Generated by Django 5.2.9 on 2025-12-25 20:09

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identifiant URL (ex: docker-basics)', unique=True)),
                ('icon', models.CharField(help_text="Nom de l'icône (ex: 🐳 ou fa-docker)", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True, help_text="Court résumé pour la carte d'aperçu")),
                ('content', markdownx.models.MarkdownxField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Cochez pour rendre visible sur le site')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorials', to='knowledge.category')),
            ],
        ),
    ]
